alertmanager:
  enabled: true

  alertmanagerSpec:
    secrets:
      - devops-lab-slack

  config:
    global:
      resolve_timeout: 5m

    route:
      group_by:
        - alertname
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
      receiver: slack-alerts
      routes:
        - receiver: "null"
          matchers:
            - alertname = "Watchdog"

    receivers:
      - name: "null"

      - name: slack-alerts
        slack_configs:
          - api_url_file: /etc/alertmanager/secrets/devops-lab-slack/slack-webhook-url
            send_resolved: true

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 3d

grafana:
  additionalDataSources:
    - name: Loki
      type: loki
      access: proxy
      url: http://loki-gateway.logging.svc.cluster.local
      isDefault: false
      editable: false
